[wokwi]
version = 1

firmware = 'atomvm_wokwi_bins/flasher_args.json'
elf = 'atomvm_wokwi_bins/flasher_args.json'


# Forward http://localhost:8180 to port 80 on the simulated ESP32:
#[[net.forward]]
#from = "localhost:8180"
#to = "target:80"
